networks:
  simnet: {}

services:
  auto_shepherd_simulation_ros2_humble:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-shepherd-simulation-ros2-humble
    stdin_open: true
    tty: true
    command: /bin/bash

    #network_mode: host
    networks: [simnet]

    privileged: true
    devices:
      - /dev:/dev

    # — Bind‑mount each git sub‑module into the workspace ————————————
    volumes:
      - ../ros2_package:/home/ros/base_ws/src/ros2_package:rw

      # Bash Scripts
      - ../bash_scripts/container:/home/ros/bash_scripts:rw

      # enable mount for gui applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      - ../rviz_config:/home/ros/.rviz2:rw

    environment:
      - BASE_WS=/home/ros/base_ws
      #- DISPLAY=${HOST_DISPLAY_VAR:-:0}
      - DISPLAY=desktop:0               # << points at the VNC server
      - QT_X11_NO_MITSHM=1


  desktop:
    image: consol/ubuntu-xfce-vnc:latest
    ports:
      - "5900:5901"          # raw VNC
      - "6080:6901"          # noVNC in browser
    volumes:
      # host repo → ~/workspace inside the desktop session
      - ../:/headless/workspace:rw

    # Tune look & feel (defaults shown)
    environment:
      - VNC_PW=0000                  # viewer password
      - VNC_COL_DEPTH=24             # colour depth
      - VNC_RESOLUTION=1920x1080     # virtual screen size

    # So the desktop starts after your app if they depend on each other
    depends_on:
      - auto_shepherd_simulation_ros2_humble
