FROM unityci/editor:ubuntu-6000.1.7f1-mac-mono-3.1.0

# Set the working directory
WORKDIR /app

# Copy the Unity project into the container
COPY . /app/

# Run the Unity tests
CMD ["/opt/Unity/Editor/Unity", "-batchmode", "-nographics", "-executeMethod", "UnityEditor.TestTools.TestRunner.Api.TestRunnerApi.ExecuteTests"] 