name: Run Tests

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

jobs:
  ros-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare files for Docker build
        run: |
          mkdir -p docker_build/src
          cp ros2_package/auto_shepherd_simulation/ros_interface.py docker_build/src/ros_interface.py
          cp -r tests docker_build/tests
          cp tests/Dockerfile.test docker_build/Dockerfile

      - name: Build ROS Test Container
        run: |
          cd docker_build
          docker build -t ros_test .

      - name: Run ROS Tests
        run: docker run ros_test
